package com.example.pfas.checker;

public enum ActionCheckerRouteCode {

	PUBLIC_WATER_UTILITY_FIRST,
	PUBLIC_WATER_INTERPRET_DIRECT_DATA,
	PUBLIC_WATER_OPTIONAL_POU_COMPARE,
	PRIVATE_WELL_TEST_FIRST,
	PRIVATE_WELL_INTERPRET_LAB_RESULT

}
