package com.example.pfas.decision;

public enum PublicWaterDecisionStatus {
	NO_DIRECT_OBSERVATIONS,
	INSUFFICIENT_BENCHMARK_CONTEXT,
	ABOVE_SELECTED_BENCHMARK,
	PRESENT_BELOW_SELECTED_BENCHMARK,
	REPORTED_BELOW_SELECTED_BENCHMARK
}
